#!/usr/bin/python3

import sys


def read_num_from_file(file_name):
    numbers = []

    try:
        with open(file_name) as f:
            number = f.readline()
            while number != "":
                number = int(number.strip())
                if number < 2:
                    sys.exit(1)
                numbers.append(number)
                number = f.readline()

    except:
        pass

    return numbers


def factoring(number):

    divisor = 2
    odd_check = 3

    if number % divisor == 0:
        quotient = number // divisor
        return "{}={}*{}".format(number, quotient, divisor)

    while odd_check < number // 2:
        if number % odd_check == 0:
            quotient = number // odd_check
            return "{}={}*{}".format(number, quotient, odd_check)
        odd_check += 2

    return "{}={}*{}".format(number, number, 1)


if __name__ == "__main__":

    if len(sys.argv) != 2:
        sys.exit(1)

    file_name = sys.argv[1]
    numbers = read_num_from_file(file_name)

    for number in numbers:
        result = factoring(number)
        print(result)
