#!/usr/bin/python3

import sys


def factoring():

    divisor = 2
    odd_check = 3

    if len(sys.argv) != 2:
        return

    file_name = sys.argv[1]
    with open(file_name) as f:
        for number in f:
            number = int(number)
            if number < 2:
                exit()
            if number % divisor == 0:
                quotient = number // divisor
                print("{}={}*{}".format(number, quotient, divisor))
                continue

            while odd_check < number // 2:
                if number % odd_check == 0:
                    quotient = number // odd_check
                    print("{}={}*{}".format(number, quotient, odd_check))
                    break
                odd_check += 2

            if odd_check == (number // 2) + 1:
                print("{}={}*{}".format(number, number, 1))


if __name__ == "__main__":

    factoring()
